import matplotlib.pyplot as plt
import geopandas
domains = ['R', 'G', 'B', "Y"]

variables = [
        'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida',
        'Georgia',
        'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
        'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
        'New Hampshire',
        'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon',
        'Pennsylvania',
        'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia',
        'Washington',
        'West Virginia', 'Wisconsin', 'Wyoming'
    ]
constraints = [
        ('Alabama', 'Florida'),
        ('Alabama', 'Georgia'),
        ('Alabama', 'Mississippi'),
        ('Alabama', 'Tennessee'),
        ('Alaska', ''),
        ('Arizona', 'California'),
        ('Arizona', 'Colorado'),
        ('Arizona', 'New Mexico'),
        ('Arizona', 'Nevada'),
        ('Arizona', 'Utah'),
        ('Arizona', 'Oregon'),
        ('Arizona', 'Idaho'),
        ('Arizona', 'Wyoming'),
        ('Arizona', 'Montana'),
        ('Arizona', 'Washington'),
        ('Arkansas', 'Louisiana'),
        ('Arkansas', 'Mississippi'),
        ('Arkansas', 'Missouri'),
        ('Arkansas', 'Oklahoma'),
        ('Arkansas', 'Tennessee'),
        ('Arkansas', 'Texas'),
        ('California', 'Oregon'),
        ('California', 'Nevada'),
        ('Colorado', 'New Mexico'),
        ('Colorado', 'Utah'),
        ('Colorado', 'Wyoming'),
        ('Colorado', 'Nebraska'),
        ('Colorado', 'Kansas'),
        ('Colorado', 'Oklahoma'),
        ('Connecticut', 'Massachusetts'),
        ('Connecticut', 'New York'),
        ('Connecticut', 'Rhode Island'),
        ('Delaware', 'Maryland'),
        ('Delaware', 'New Jersey'),
        ('Delaware', 'Pennsylvania'),
        ('Florida', 'Georgia'),
        ('Georgia', 'Tennessee'),
        ('Georgia', 'North Carolina'),
        ('Georgia', 'South Carolina'),
        ('Hawaii', ''),
        ('Idaho', 'Washington'),
        ('Idaho', 'Oregon'),
        ('Idaho', 'Nevada'),
        ('Idaho', 'Utah'),
        ('Idaho', 'Montana'),
        ('Idaho', 'Wyoming'),
        ('Illinois', 'Indiana'),
        ('Illinois', 'Iowa'),
        ('Illinois', 'Kentucky'),
        ('Illinois', 'Michigan'),
        ('Illinois', 'Missouri'),
        ('Illinois', 'Wisconsin'),
        ('Indiana', 'Kentucky'),
        ('Indiana', 'Michigan'),
        ('Indiana', 'Ohio'),
        ('Iowa', 'Minnesota'),
        ('Iowa', 'Missouri'),
        ('Iowa', 'Nebraska'),
        ('Iowa', 'South Dakota'),
        ('Iowa', 'Wisconsin'),
        ('Kansas', 'Missouri'),
        ('Kansas', 'Nebraska'),
        ('Kansas', 'Oklahoma'),
        ('Kansas', 'Colorado'),
        ('Kentucky', 'Missouri'),
        ('Kentucky', 'Ohio'),
        ('Kentucky', 'Tennessee'),
        ('Kentucky', 'Virginia'),
        ('Kentucky', 'West Virginia'),
        ('Louisiana', 'Arkansas'),
        ('Louisiana', 'Mississippi'),
        ('Louisiana', 'Texas'),
        ('Maine', 'New Hampshire'),
        ('Maryland', 'Delaware'),
        ('Maryland', 'Pennsylvania'),
        ('Maryland', 'Virginia'),
        ('Maryland', 'West Virginia'),
        ('Massachusetts', 'Connecticut'),
        ('Massachusetts', 'New Hampshire'),
        ('Massachusetts', 'New York'),
        ('Massachusetts', 'Rhode Island'),
        ('Massachusetts', 'Vermont'),
        ('Michigan', 'Indiana'),
        ('Michigan', 'Ohio'),
        ('Michigan', 'Wisconsin'),
        ('Minnesota', 'North Dakota'),
        ('Minnesota', 'South Dakota'),
        ('Minnesota', 'Wisconsin'),
        ('Mississippi', 'Arkansas'),
        ('Mississippi', 'Louisiana'),
        ('Mississippi', 'Tennessee'),
        ('Missouri', 'Illinois'),
        ('Missouri', 'Iowa'),
        ('Missouri', 'Kansas'),
        ('Missouri', 'Kentucky'),
        ('Missouri', 'Nebraska'),
        ('Missouri', 'Oklahoma'),
        ('Missouri', 'Tennessee'),
        ('Montana', 'Idaho'),
        ('Montana', 'North Dakota'),
        ('Montana', 'South Dakota'),
        ('Montana', 'Wyoming'),
        ('Nebraska', 'Kansas'),
        ('Nebraska', 'Colorado'),
        ('Nebraska', 'Iowa'),
        ('Nebraska', 'South Dakota'),
        ('Nebraska', 'Wyoming'),
        ('Nevada', 'California'),
        ('Nevada', 'Arizona'),
        ('Nevada', 'Utah'),
        ('Nevada', 'Idaho'),
        ('Nevada', 'Oregon'),
        ('New Hampshire', 'Maine'),
        ('New Hampshire', 'Massachusetts'),
        ('New Hampshire', 'Vermont'),
        ('New Jersey', 'Delaware'),
        ('New Jersey', 'Pennsylvania'),
        ('New Jersey', 'New York'),
        ('New Mexico', 'Arizona'),
        ('New Mexico', 'Colorado'),
        ('New Mexico', 'Oklahoma'),
        ('New Mexico', 'Texas'),
        ('New Mexico', 'Utah'),
        ('New York', 'Connecticut'),
        ('New York', 'Massachusetts'),
        ('New York', 'Pennsylvania'),
        ('New York', 'Rhode Island'),
        ('North Carolina', 'Tennessee'),
        ('North Carolina', 'Virginia'),
        ('North Dakota', 'Minnesota'),
        ('North Dakota', 'Montana'),
        ('North Dakota', 'South Dakota'),
        ('Ohio', 'Indiana'),
        ('Ohio', 'Kentucky'),
        ('Ohio', 'Michigan'),
        ('Ohio', 'Pennsylvania'),
        ('Ohio', 'West Virginia'),
        ('Oklahoma', 'Arkansas'),
        ('Oklahoma', 'Colorado'),
        ('Oklahoma', 'Kansas'),
        ('Oklahoma', 'Missouri'),
        ('Oklahoma', 'New Mexico'),
        ('Oklahoma', 'Texas'),
        ('Oregon', 'California'),
        ('Oregon', 'Idaho'),
        ('Oregon', 'Nevada'),
        ('Oregon', 'Washington'),
        ('Pennsylvania', 'Delaware'),
        ('Pennsylvania', 'Maryland'),
        ('Pennsylvania', 'New Jersey'),
        ('Pennsylvania', 'New York'),
        ('Pennsylvania', 'Ohio'),
        ('Rhode Island', 'Connecticut'),
        ('Rhode Island', 'Massachusetts'),
        ('Rhode Island', 'Vermont'),
        ('South Carolina', 'Georgia'),
        ('South Carolina', 'North Carolina'),
        ('South Carolina', 'Tennessee'),
        ('South Carolina', 'Virginia'),
        ('South Dakota', 'Iowa'),
        ('South Dakota', 'Minnesota'),
        ('South Dakota', 'Montana'),
        ('South Dakota', 'Nebraska'),
        ('South Dakota', 'North Dakota'),
        ('Tennessee', 'Alabama'),
        ('Tennessee', 'Arkansas'),
        ('Tennessee', 'Georgia'),
        ('Tennessee', 'Kentucky'),
        ('Tennessee', 'Mississippi'),
        ('Tennessee', 'Missouri'),
        ('Tennessee', 'Virginia'),
        ('Texas', 'Arkansas'),
        ('Texas', 'Louisiana'),
        ('Texas', 'New Mexico'),
        ('Texas', 'Oklahoma'),
        ('Texas', 'Kansas'),
        ('Texas', 'Colorado'),
        ('Utah', 'Arizona'),
        ('Utah', 'Colorado'),
        ('Utah', 'Idaho'),
        ('Utah', 'Nevada'),
        ('Utah', 'New Mexico'),
        ('Utah', 'Wyoming'),
        ('Vermont', 'New Hampshire'),
        ('Vermont', 'Massachusetts'),
        ('Vermont', 'New York'),
        ('Vermont', 'Rhode Island'),
        ('Virginia', 'Kentucky'),
        ('Virginia', 'Maryland'),
        ('Virginia', 'North Carolina'),
        ('Virginia', 'South Carolina'),
        ('Virginia', 'Tennessee'),
        ('Virginia', 'West Virginia'),
        ('Washington', 'Idaho'),
        ('Washington', 'Oregon'),
        ('West Virginia', 'Kentucky'),
        ('West Virginia', 'Maryland'),
        ('West Virginia', 'Ohio'),
        ('West Virginia', 'Pennsylvania'),
        ('West Virginia', 'Virginia'),
        ('Wisconsin', 'Illinois'),
        ('Wisconsin', 'Iowa'),
        ('Wisconsin', 'Michigan'),
        ('Wisconsin', 'Minnesota'),
        ('Wyoming', 'Colorado'),
        ('Wyoming', 'Idaho'),
        ('Wyoming', 'Montana'),
        ('Wyoming', 'Nebraska'),
        ('Wyoming', 'South Dakota'),
        ('Wyoming', 'Utah')
    ]

solution={'Alabama': 'R', 'Alaska': 'R', 'Arizona': 'R', 'Arkansas': 'R', 'California': 'G', 'Colorado': 'G', 'Connecticut': 'R', 'Delaware': 'R', 'Florida': 'G', 'Georgia': 'B', 'Hawaii': 'Y', 'Idaho': 'R', 'Illinois': 'B', 'Indiana': 'Y', 'Iowa': 'G', 'Kansas': 'R', 'Kentucky': 'R', 'Louisiana': 'B', 'Maine': 'G', 'Maryland': 'G', 'Massachusetts': 'B', 'Michigan': 'R', 'Minnesota': 'B', 'Mississippi': 'Y', 'Missouri': 'Y', 'Montana': 'B', 'Nebraska': 'B', 'Nevada': 'Y', 'New Hampshire': 'Y', 'New Jersey': 'G', 'New Mexico': 'Y', 'New York': 'Y', 'North Carolina': 'Y', 'North Dakota': 'Y', 'Ohio': 'G', 'Oklahoma': 'B', 'Oregon': 'B', 'Pennsylvania': 'B', 'Rhode Island': 'G', 'South Carolina': 'R', 'South Dakota': 'R', 'Tennessee': 'G', 'Texas': 'G', 'Utah': 'B', 'Vermont': 'R', 'Virginia': 'B', 'Washington': 'Y', 'West Virginia': 'Y', 'Wisconsin': 'Y', 'Wyoming': 'Y'}
print("Ready to plot map for Canda")
path = "./states_21basic/"
# # load the shape file using geopandas
states = geopandas.read_file(path + 'states.shp')
states = states.to_crs("EPSG:3395")
ax2 = states.boundary.plot(figsize=(12, 12), edgecolor=u'gray')
for k, v in solution.items():

    print(states)

    if v == 'R':
        states[states.STATE_NAME == k].plot(edgecolor=u'gray', color='yellow', ax=ax2)
    elif v == 'B':
        states[states.STATE_NAME == k].plot(edgecolor=u'gray', color='blue', ax=ax2)
    elif v == 'G':
        states[states.STATE_NAME == k].plot(edgecolor=u'gray', color='green', ax=ax2)
    else:
        states[states.STATE_NAME == k].plot(edgecolor=u'gray', color='red', ax=ax2)

plt.show()




